routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', 'HomeController@welcome');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/section/{id}', 'HomeController@section');
Route::get('/article/{id}', 'HomeController@article');
Route::resource('/articles'   , 'articlesController')->middleware('auth');

resources/views/article.blade.php
@extends('layouts.app')
@section('content')
<div class="container" >
    <div class="row " >
        <div class="col-md-12">
            <div class="card" >
                <div class="card-header">
                  <div class="links">
                    @foreach($sections as $section)
                       <a href="{{url('section')}}/{{$section->id}}"> {{$section->section_title}} </a> 
                    @endforeach
                  </div>
                </div>                 
                <div class="card-body" >                
                       <div class="row" >
                       <img src="{{url($article->article_thumb)}}" >
                       </div>
                       <div class="row" >
                       {!! $article->article_details !!}
                       </div>
                </div>                 
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/articles_add.blade.php
@extends('layouts.app')
<script  src="{{url('js/ck/ckeditor.js')}}"></script>
<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
<script  src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script  src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">New Article</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                   

    
                    <form class="form-material m-t-40" name="author" method="POST" action="{{url('articles')}}" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    <div class="form-group">
                       <lable>Title</lable>
                       <input type="text" name="article_title" id="article_title" class="form-control" value="{{ old('article_title') }}">
                       @if ($errors->has('article_title')) <div class="text-danger">{{ $errors->first('article_title') }}</div> @endif
                    </div>
                    <div class="row">
                      <div class="col-md-4">
                           <div class="form-group">
                              <lable>Article Type</lable>
                              <select class="form-control" name="article_type" id="article_type" > 
                                 <option value="2" >Article</option>
                                 <option value="1">Featured Article</option>
                              </select>
                              @if ($errors->has('article_type')) <div class="text-danger">{{ $errors->first('article_type') }}</div> @endif
                           </div>
                      </div>
                      <div class="col-md-4">
                           <div class="form-group">
                              <lable>Article Section</lable>
                              <select class="form-control" name="section_id" id="section_id">
                                 @foreach($sections as $section)
                                     <option value="{{$section->id}}">{{$section->section_title}}</option>
                                 @endforeach                                 
                              </select>
                              @if ($errors->has('section_id')) <div class="text-danger">{{ $errors->first('section_id') }}</div> @endif
                           </div>
                      </div>
                      <div class="col-md-4">
                           <div class="form-group">
                              <lable>Article Order</lable>
                              <input type="number" min="1" name="article_order" id="article_order" class="form-control" value="{{ old('article_order') }}">
                              @if ($errors->has('article_order')) <div class="text-danger">{{ $errors->first('article_order') }}</div> @endif
                           </div>
                      </div>
                    </div>
                        <div class="form-group">
                              <lable>Article Image</lable>
                              <input type="file" name="article_thumb" id="article_thumb" class="form-control" value="{{ old('article_thumb') }}">
                              @if ($errors->has('article_thumb')) <div class="text-danger">{{ $errors->first('article_thumb') }}</div> @endif
                        </div>
                    <div class="form-group">
                                    <lable>Details</lable>
                                    <textarea name="article_details" id="editor1" rows="10" cols="80">{{ old('article_details') }}</textarea>
                                    @if ($errors->has('article_details')) <div class="text-danger">{{ $errors->first('article_details') }}</div>     @endif
                                    <script src="//cdn.ckeditor.com/4.11.1/basic/ckeditor.js"></script>

                                    <script type="text/javascript">
                                        CKEDITOR.replace( 'editor1', {
                                        });
                                        
                                    </script>
        
                                </div>

                                <div class="form-group">
                                 <button type="submit" class="btn btn-success">Add New Article</button>
                                </div>
                                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>

resources/views/articles_edit.blade.php
@extends('layouts.app')
<script  src="{{url('js/ck/ckeditor.js')}}"></script>
<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
<script  src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script  src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">New Article</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                   

    
                    <form action="{{ route('articles.update', $article->article_id) }}" method="post" enctype="multipart/form-data">
                     {{ csrf_field() }}
                     {{ method_field('PUT') }}
                    <div class="form-group">
                       <lable>Title</lable>
                       <input type="text" name="article_title" id="article_title" class="form-control" value="{{$article->article_title }}">
                       @if ($errors->has('article_title')) <div class="text-danger">{{ $errors->first('article_title') }}</div> @endif
                    </div>
                    <div class="row">
                      <div class="col-md-4">
                           <div class="form-group">
                              <lable>Article Type</lable>
                              <select class="form-control" name="article_type" id="article_type" > 
                                 <option value="1" {{isset($article->article_type)==2 ? "selected" : "" }}>Article</option>
                                 <option value="2" {{isset($article->article_type)==1 ? "selected" : "" }}>Featured Article</option>
                              </select>
                              @if ($errors->has('article_type')) <div class="text-danger">{{ $errors->first('article_type') }}</div> @endif
                           </div>
                      </div>
                      <div class="col-md-4">
                           <div class="form-group">
                              <lable>Article Section</lable>
                              <select class="form-control" name="section_id" id="section_id">
                                 @foreach($sections as $section)
                                     <option value="{{$section->id}}" {{isset($article->section_id)==$section->id ? "selected" : "" }}>{{$section->section_title}}</option>
                                 @endforeach                                 
                              </select>
                              @if ($errors->has('section_id')) <div class="text-danger">{{ $errors->first('section_id') }}</div> @endif
                           </div>
                      </div>
                      <div class="col-md-4">
                           <div class="form-group">
                              <lable>Article Order</lable>
                              <input type="number" min="1" name="article_order" id="article_order" class="form-control" value="{{ $article->article_order }}">
                              @if ($errors->has('article_order')) <div class="text-danger">{{ $errors->first('article_order') }}</div> @endif
                           </div>
                      </div>
                    </div>
                        <div class="form-group">
                              <lable>Article Image</lable>
                              <input type="file" name="article_thumb" id="article_thumb" class="form-control" >
                              <img src="{{url($article->article_thumb)}}" />
                              @if ($errors->has('article_thumb')) <div class="text-danger">{{ $errors->first('article_thumb') }}</div> @endif
                        </div>
                    <div class="form-group">
                                    <lable>Details</lable>
                                    <textarea name="article_details" id="editor1" rows="10" cols="80">{{ $article->article_details }}</textarea>
                                    @if ($errors->has('article_details')) <div class="text-danger">{{ $errors->first('article_details') }}</div>     @endif
                                    <script src="//cdn.ckeditor.com/4.11.1/basic/ckeditor.js"></script>

                                    <script type="text/javascript">
                                        CKEDITOR.replace( 'editor1', {
                                        });
                                        
                                    </script>
        
                                </div>

                                <div class="form-group">
                                 <button type="submit" class="btn btn-success">Update Article</button>
                                </div>
                                </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>

resources/views/home.blade.php
@extends('layouts.app')
<script  src="{{url('js/ck/ckeditor.js')}}"></script>
<link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css">
<script  src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script  src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <div class="row">
                         <div class="col-lg-4 col-md-6">
                             <div class="card " style="background-color:#968cec;">
                                 <div class="card-body">
                                     <div class="d-flex flex-row">
                                         <div class="align-self-center m-l-20">
                                             <h3 class="text-white m-b-0">{{$stastics['articles']}}</h3>
                                             <h2 class="text-white m-b-0">Articles</h2>
                                         </div>
                                     </div>
                                 </div>
                             </div>
                         </div>
                         <div class="col-lg-4 col-md-6">
                             <div class="card" style="background-color:#1976d2;">
                                 <div class="card-body">
                                     <div class="d-flex flex-row">
                                         <div class="align-self-center m-l-20">
                                             <h3 class="text-white m-b-0 ">{{$stastics['featured_articles']}}</h3>
                                             <h2 class="text-white m-b-0">featured articles</h2>
                                         </div>
                                     </div>
                                 </div>
                             </div>
                         </div>
                    </div>

                    <br><br>
                    
                    <div class="row">
                        <div class="col-md-12">
                        <a class="btn btn-info" href="{{url('articles/create')}}"> <i class="mdi mdi-library-plus"></i>  Add New Article</a>
                        </div>
                    </div>
                    
                    <table id="example" class="display" style="width:100%">
        <thead>
            <tr>
                <th>Article Title</th>
                <th>Article Type</th>
                <th>Article Section</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            
              @foreach($articles as $article)
                <tr>
                  <td>{{$article->article_title }}</td>
                  <td>@if($article->article_type == 1)<p>Article</p>@else <p>Featured Article</p> @endif</td>
                  <td>{{$article->section_id }}</td>
                  <td>

                  <a href="{{ route('articles.edit',$article->article_id) }}" class="btn waves-effect waves-light btn-outline-info" data-toggle="tooltip" data-placement="top" title="" >Edit</a>

                   
                   <form action="{{url('articles', [$article->article_id])}}" method="POST" >
                   <input type="hidden" name="_method" value="DELETE">
                   <input type="hidden" name="_token" value="{{ csrf_token() }}">
                   <button class="btn btn-danger">Delete</button>
                   
                   </form>
                  </td>
                </tr>
              @endforeach
            
        </tbody>
            
            
    </table>

    
                    
                    <!-- <div class="form-group">
                                    <lable>الموضـــوع</lable>
                                    <textarea name="details" id="editor1" rows="10" cols="80"></textarea>
                                    @if ($errors->has('details')) <div class="text-danger">{{ $errors->first('details') }}</div>     @endif
                                    <script src="//cdn.ckeditor.com/4.11.1/basic/ckeditor.js"></script>

                                    <script type="text/javascript">
                                        CKEDITOR.replace( 'editor1', {
                                        });
                                        
                                    </script>
        
                                </div>
                </div> -->
            </div>
        </div>
    </div>
</div>
@endsection
<script>
$(document).ready(function() {
    $('#example').DataTable();
} );
</script>

resources/views/section.blade.php
@extends('layouts.app')
@section('content')
<div class="container" >
    <div class="row " >
        <div class="col-md-12">
            <div class="card" >
                <div class="card-header">
                  <div class="links">
                    @foreach($sections as $section)
                       <a href="{{url('section/')}}/{{$section->id}}"> {{$section->section_title}} </a> 
                    @endforeach
                  </div>
                </div>                 
                <div class="card-body">
                    @if(isset($articles))
                    @foreach($articles as $article)
                       <div class="row" >
                            <div class="col-md-2" > <img src="{{url($article->article_thumb)}}" width="60%"/></div>
                            <div class="col-md-3" ><a href="{{url('article')}}/{{$article->article_id}}">{{$article->article_title}}</a></div>                                                
                       </div>
                       <hr>
                    @endforeach     
                    
                    @endif               1 
                                  
                </div>                 
            </div>
        </div>
    </div>
</div>
@endsection